params:
  batch_size: 512
  shuffle: true
  optimizer: Adam
  learning_rate: 0.003
  epochs: 5
  train_steps: 10
  embed_size: 300
  checkpoint_frequency: 10
  n_neg_samples: 4
  print_step: 1
  max_window_size: 4
paths:
  model_dir: weights
  data_dir: data/
  data_path: data/datasets/text8
